version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel-network
    depends_on:
      - database
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  database:
    image: mysql:latest
    container_name: mysql
    platform: linux/arm64 # 加上這一行，指定為 arm64 平台
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "8000:80"
    networks:
      - laravel-network
    depends_on:
      - app

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
