###  2.0.0 test with en locale

GET http://localhost:8000/api/v2/day-of-the-week?date=2025-04-22&locale=en

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        client.assert(
            response.contentType.mimeType === "application/json",
            "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "date": "2025-04-22",
            "locale":"en",
            "dayOfWeek": "Tuesday"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}

###  2.0.0 test with zh_TW locale

GET http://localhost:8000/api/v2/day-of-the-week?date=2025-04-22&locale=zh_TW

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "date": "2025-04-22",
            "locale":"zh_TW",
            "dayOfWeek": "星期二"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}

###  2.0.0 test with ja locale

GET http://localhost:8000/api/v2/day-of-the-week?date=2025-04-22&locale=ja

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "date": "2025-04-22",
            "locale":"ja",
            "dayOfWeek": "火曜日"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}

###  2.0.0 test with default locale

GET http://localhost:8000/api/v2/day-of-the-week?date=2025-04-22

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Response body is correct", function () {
        const body = JSON.stringify(response.body);
        const expect = JSON.stringify({
            "date": "2025-04-22",
            "locale":"en",
            "dayOfWeek": "Tuesday"
        });
        client.assert(
            body === expect,
            "received wrong body'" + body + "'"
        );
    });
%}
